python -m src.train \
  --device 0 \
  --batch_size 128 \
  --iters_per_epoch 50 \
  --epochs 1000 \
  --lr 8e-4 \
  --seed 0 \
  --fold_idx 5 \
  --model exgat \
  --num_layers 3 \
  --hidden_dim 256 \
  --final_dropout 0.5 \
  --layer_dropout 0.15 \
  --graph_pooling_type sum \
  --patience 20 \
  --adjacency 2 \
  --self_connect False \
  --use_multiscale_fusion True \
  --use_special_pooling True